"""
GenVM deploys a single file's raw bytes as the contract code -- it has no
access to sibling files in this repo, so `from contracts.normalizer import
...` (which works fine locally and in pytest) fails inside the runtime
with `ModuleNotFoundError: No module named 'contracts'`.

This script inlines contracts/normalizer.py into contracts/weblock.py
to produce contracts/weblock_bundle.py, a single self-contained
file, which is what actually gets deployed. The source-of-truth, unit-tested
normalizer.py stays exactly as it is for local development and pytest; this
only reassembles its already-tested body, it doesn't rewrite any logic.

Run: python deploy/build_bundle.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
OUT_PATH = CONTRACTS / "weblock_bundle.py"

DEPENDS_HEADER = (
    '# { "Depends": "py-genlayer:'
    '1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }'
)

DROP_LINES = {
    "import hashlib",
    "import re",
    "from dataclasses import dataclass",
    "from genlayer import *",
    "from contracts.normalizer import excerpt_present, normalize_and_hash, normalize_text, normalize_url",
}


def strip_leading_docstring(source: str) -> str:
    lines = source.split("\n")
    i = 0
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    if i < len(lines) and lines[i].lstrip().startswith('"""'):
        quote = '"""'
        first_line = lines[i]
        i += 1
        if first_line.count(quote) < 2:
            while i < len(lines) and quote not in lines[i]:
                i += 1
            i += 1
    return "\n".join(lines[i:])


def strip_known_import_lines(source: str) -> str:
    kept = [line for line in source.split("\n") if line.strip() not in DROP_LINES]
    return "\n".join(kept)


def body_of(filename: str) -> str:
    source = (CONTRACTS / filename).read_text(encoding="utf-8")
    source = strip_leading_docstring(source)
    source = strip_known_import_lines(source)
    return source.strip("\n")


def main() -> None:
    weblock_source = (CONTRACTS / "weblock.py").read_text(encoding="utf-8")
    lines = weblock_source.split("\n")
    assert lines[0].strip().startswith('# { "Depends"')
    weblock_source = "\n".join(lines[1:])
    weblock_body = strip_known_import_lines(strip_leading_docstring(weblock_source))

    sections = [
        DEPENDS_HEADER,
        (
            '"""\n'
            "WebLock -- bundled, deployable single file.\n\n"
            "Generated by deploy/build_bundle.py from contracts/normalizer.py "
            "and\nweblock.py. Do not hand-edit -- edit the source modules "
            "and\nregenerate. See those files for documentation; this file "
            "exists\npurely because GenVM deploys a single file with no "
            "access to sibling\nlocal modules.\n\"\"\""
        ),
        "import hashlib",
        "import re",
        "from dataclasses import dataclass",
        "",
        "from genlayer import *",
        "",
        body_of("normalizer.py"),
        weblock_body.strip("\n"),
    ]

    bundle = "\n\n\n".join(s.strip("\n") for s in sections) + "\n"
    OUT_PATH.write_text(bundle, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH} ({len(bundle)} bytes)")


if __name__ == "__main__":
    main()
