# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }


"""
WebLock -- bundled, deployable single file.

Generated by deploy/build_bundle.py from contracts/normalizer.py and
weblock.py. Do not hand-edit -- edit the source modules and
regenerate. See those files for documentation; this file exists
purely because GenVM deploys a single file with no access to sibling
local modules.
"""


import hashlib


import re


from dataclasses import dataclass





from genlayer import *





_WHITESPACE_RE = re.compile(r"\s+")

# "3 minutes ago", "posted 2 hours ago", "updated 1 day ago"
_RELATIVE_TIME_RE = re.compile(
    r"\b\d+\s+(?:second|minute|hour|day|week|month|year)s?\s+ago\b",
    re.IGNORECASE,
)

# "1,234 views", "42 comments", "3.2k likes", "128 upvotes"
_COUNTER_RE = re.compile(
    r"\b[\d,]+(?:\.\d+)?[kKmM]?\+?\s+"
    r"(?:views?|comments?|likes?|shares?|reads?|upvotes?|downvotes?|"
    r"downloads?|replies?|reactions?)\b",
    re.IGNORECASE,
)

# Query-string keys that identify a visitor/session/campaign rather than
# the actual resource, so they don't belong in a content-identity hash.
_TRACKING_PARAM_KEYS = frozenset(
    [
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_term",
        "utm_content",
        "gclid",
        "fbclid",
        "msclkid",
        "mc_cid",
        "mc_eid",
        "ref",
        "referrer",
        "session",
        "sessionid",
        "session_id",
        "sid",
        "_ga",
        "igshid",
        "spm",
    ]
)


@dataclass
class NormalizedPage:
    normalized_text: str
    text_hash: str


def normalize_text(text: str) -> str:
    """
    Collapse whitespace, strip relative-time stamps and engagement
    counters, and lowercase. This is deliberately aggressive: the goal
    is content-identity for hashing, not a readable diff.
    """
    if text is None:
        return ""
    normalized = _RELATIVE_TIME_RE.sub(" ", text)
    normalized = _COUNTER_RE.sub(" ", normalized)
    normalized = _WHITESPACE_RE.sub(" ", normalized)
    return normalized.strip().lower()


def normalize_url(url: str) -> str:
    """
    Drop the fragment and any tracking query params, so
    example.com/a?utm_source=x and example.com/a are treated as the same
    resource. Remaining query params are kept but sorted, so param order
    (which shouldn't vary for the same logical request, but might) can't
    silently change the hash.
    """
    if url is None:
        return ""
    url = url.strip()
    url = url.split("#", 1)[0]

    if "?" not in url:
        return url

    base, query = url.split("?", 1)
    if not query:
        return base

    kept_params = []
    for pair in query.split("&"):
        if not pair:
            continue
        key = pair.split("=", 1)[0].lower()
        if key in _TRACKING_PARAM_KEYS:
            continue
        kept_params.append(pair)

    if not kept_params:
        return base

    kept_params.sort()
    return base + "?" + "&".join(kept_params)


def hash_text(text: str) -> str:
    """Deterministic content hash of already-normalized text."""
    return "0x" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def hash_bytes(data: bytes) -> str:
    """Deterministic hash of raw bytes, e.g. a screenshot."""
    if data is None:
        data = b""
    return "0x" + hashlib.sha256(data).hexdigest()


def normalize_and_hash(text: str) -> NormalizedPage:
    normalized = normalize_text(text)
    return NormalizedPage(normalized_text=normalized, text_hash=hash_text(normalized))


def excerpt_present(page_text: str, excerpt: str) -> bool:
    """
    True if `excerpt` appears in `page_text` after both are normalized
    the same way. Guards against freezing a claim about a page that
    never actually contained the excerpt in the first place.
    """
    normalized_page = normalize_text(page_text)
    normalized_excerpt = normalize_text(excerpt)
    if not normalized_excerpt:
        return False
    return normalized_excerpt in normalized_page


@allow_storage
@dataclass
class Snapshot:
    url: str
    excerpt: str
    text_hash: str
    excerpt_hash: str
    submitter: Address
    status: str


class WebLock(gl.Contract):
    snapshots: TreeMap[str, Snapshot]
    by_submitter: TreeMap[Address, DynArray[str]]

    def __init__(self):
        pass

    def _snapshot_id(self, url: str, excerpt: str) -> str:
        material = "\x00".join(
            [
                gl.message.sender_address.as_hex,
                str(gl.message.chain_id),
                normalize_url(url),
                normalize_text(excerpt),
            ]
        ).encode("utf-8")
        return hashlib.sha256(material).hexdigest()[:24]

    @gl.public.write
    def freeze(self, url: str, excerpt: str) -> str:
        """
        Fetch `url`, confirm `excerpt` actually appears on the page, and
        record a normalized content hash under a snapshot id derived
        from the sender, url, and excerpt. Raises if the excerpt is not
        found, or if this exact (sender, url, excerpt) combination has
        already been frozen.
        """
        snapshot_id = self._snapshot_id(url, excerpt)
        if snapshot_id in self.snapshots:
            raise gl.vm.UserError(f"already frozen: {snapshot_id}")

        normalized_url = normalize_url(url)

        def fetch_and_hash() -> dict:
            page_text = gl.nondet.web.render(normalized_url, mode="text")
            normalized = normalize_and_hash(page_text)
            return {
                "text_hash": normalized.text_hash,
                "excerpt_found": excerpt_present(page_text, excerpt),
            }

        result = gl.eq_principle.strict_eq(fetch_and_hash)

        if not result["excerpt_found"]:
            raise gl.vm.UserError(f"excerpt not found on page: {url}")

        excerpt_hash = normalize_and_hash(excerpt).text_hash

        self.snapshots[snapshot_id] = Snapshot(
            url=url,
            excerpt=excerpt,
            text_hash=result["text_hash"],
            excerpt_hash=excerpt_hash,
            submitter=gl.message.sender_address,
            status="frozen",
        )
        self.by_submitter.get_or_insert_default(gl.message.sender_address).append(
            snapshot_id
        )

        return snapshot_id

    @gl.public.write
    def verify(self, snapshot_id: str) -> str:
        """
        Re-fetch the frozen page and classify what happened since
        freeze(): "unchanged", "changed_cosmetic", "changed_material",
        or "dead". Updates and returns the snapshot's status.
        """
        if snapshot_id not in self.snapshots:
            raise gl.vm.UserError(f"unknown snapshot: {snapshot_id}")
        snapshot = self.snapshots[snapshot_id]
        url = snapshot.url
        excerpt = snapshot.excerpt

        def fetch_current() -> dict:
            try:
                page_text = gl.nondet.web.render(url, mode="text")
            except Exception:
                return {"dead": True, "text_hash": "", "excerpt_found": False}
            normalized = normalize_and_hash(page_text)
            return {
                "dead": False,
                "text_hash": normalized.text_hash,
                "excerpt_found": excerpt_present(page_text, excerpt),
            }

        result = gl.eq_principle.strict_eq(fetch_current)

        if result["dead"]:
            status = "dead"
        elif result["text_hash"] == snapshot.text_hash:
            status = "unchanged"
        elif result["excerpt_found"]:
            status = "changed_cosmetic"
        else:
            status = self._judge_material_change(url, excerpt)

        snapshot.status = status
        return status

    def _judge_material_change(self, url: str, excerpt: str) -> str:
        """
        The excerpt is no longer found verbatim on the page. That alone
        doesn't prove the meaning changed (a typo fix reads the same as
        a retraction under plain substring matching), so this asks
        GenVM's own non-comparative judgment to classify the page.

        `get_input` supplies context only -- GenVM performs the actual
        LLM classification internally from `task`/`criteria`, and
        validators independently judge the leader's answer against
        `criteria` rather than requiring identical text. The contract
        does not build or call an LLM prompt itself here; doing so was
        an earlier bug, caught by a local direct-mode test that failed
        with "Unknown gl_call request type: ExecPromptTemplate" once it
        became clear this method issues its own internal host call
        rather than routing through gl.nondet.exec_prompt.
        """

        def get_input() -> str:
            page_text = gl.nondet.web.render(url, mode="text")
            return f"Original excerpt:\n{excerpt}\n\nCurrent page text:\n{page_text}"

        verdict = gl.eq_principle.prompt_non_comparative(
            get_input,
            task=(
                "Classify whether the current page text still conveys the "
                'same substance as the original excerpt. Respond with '
                'exactly one word: "unchanged" or "changed".'
            ),
            criteria=(
                'The response must be exactly one word, either "unchanged" '
                'or "changed". Answer "unchanged" only if the core factual '
                "claim or commitment in the original excerpt still holds "
                "according to the current page text. Minor rewording, "
                "formatting, or unrelated changes elsewhere on the page do "
                'not count. Answer "changed" if the substance of the '
                "excerpt has shifted, been retracted, or been contradicted."
            ),
        )
        normalized_verdict = (verdict or "").strip().lower()
        return "changed_cosmetic" if "unchanged" in normalized_verdict else "changed_material"

    @gl.public.view
    def get(self, snapshot_id: str) -> dict:
        snapshot = self.snapshots[snapshot_id]
        return {
            "url": snapshot.url,
            "excerpt": snapshot.excerpt,
            "text_hash": snapshot.text_hash,
            "excerpt_hash": snapshot.excerpt_hash,
            "submitter": snapshot.submitter.as_hex,
            "status": snapshot.status,
        }

    @gl.public.view
    def get_by_submitter(self, submitter: str) -> dict:
        # GenLayer's calldata layer auto-decodes an address-shaped string
        # into an Address before it reaches this method, regardless of the
        # `str` type hint, so wrapping it again in Address(...) crashes
        # with "cannot convert 'Address' object to bytes". Confirmed live
        # on Bradbury; handle both shapes rather than assume one.
        addr = submitter if isinstance(submitter, Address) else Address(submitter)
        ids = self.by_submitter.get(addr, [])
        return {"snapshot_ids": list(ids)}
